name: tuple
version: 2.0.0-nullsafety.0

description: Tuple data structure
homepage: https://github.com/google/tuple.dart

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  quiver: ^3.0.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
