name: tuple
version: 1.0.1+1
authors:
- Boris Kaul <localvoid@gmail.com>
- Kwang Yul Seo <kwangyul.seo@gmail.com>
description: Tuple data structure
homepage: https://github.com/kseo/tuple
environment:
  sdk: '>=1.6.0'
dependencies:
  quiver: '>=0.22.0 <0.27.0'
dev_dependencies:
  test: any
