name: tuple
version: 1.0.4-dev

description: Tuple data structure
homepage: https://github.com/google/tuple.dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  quiver: '>=0.22.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.2.0
  test: '>=1.0.0 <2.0.0'
